tasks:

  update_db:

    user: "root"
    hosts: ["192.169.14.4", "192.168.14.5"]
    groups: []  # Can be used to specify a group where a process is applied to all hosts
    schedule: 00 # Can be used to schedule a task to a specific time
    persistSession: true # Should the session perform a session.Run(cmd) or session.Start(cmd)
    logs:
      logging: true
      logFile: /path/to/log_file

    instructions:
      - name: instruction1
        type: fileTransfer  #fileTransfer / command
        file_src: ./local/path
        file_dst: ~/remote/data/path
        dependencies:  # Specify
         - host: "192.167.14.12"
           task: "Install webserver"
           step_name: "endpoint_test"
         - host: "192.168.14.5"
           task: "Install webserver"
           step_name: "deploy_web"
        retries: 3

      - name: instruction2
        type: command
        command: "./script.sh"
        retries: 1

  update_web:

    user: "meriksen"
    hosts: ["192.169.14.4"]
    groups: ["staging", "db"]

    instructions:
      - name: instruction1
        type: command
        command: "cd repo && docker-compose up -d"
        retries: 2