
hosts:

  server1:
    fqdn: server1.bfs.com
    ipAddr: 192.169.14.4
    pubKey: path/to/key_file.pub
    groups: ["db"]

  server2:
    fqdn: server2.bfs.com
    ipAddr: 192.168.14.5
    pubKey: path/to/key_file2.pub
    groups: [ "db", "web" ]

tasks:

  update_db:

    user: "root"
    hosts: ["123.123.123.123"]
    groups: ["db"]  # Can be used to specify a group where a process is applied to all hosts
    schedule: 00 # Can be used to schedule a task to a specific time
    persistSession: true # Should the session perform a session.Run(cmd) or session.Start(cmd)
    logs:
      logging: true
      logFile: /path/to/log_file

    instructions:
      - name: instruction1
        type: fileTransfer  #fileTransfer / command
        file_src: ./local/path
        file_dst: ~/remote/data/path
        dependencies:  # Specify
          - host: "123.123.123.123"
            task: test-web
            step_name: "Pre-commit hooks"
          - host: "123.123.123.123"
            task: test-web
            step_name: "Pre-commit hooks"
        retries: 3

      - name: instruction2
        type: command
        command: "./script.sh"
        retries: 1

  update_web:

    user: "meriksen"
    hosts: [ "122.123.123.123" ]
    groups: ["web"]